# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
$:.unshift("~/.rubymotion/rubymotion-templates")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'sample-app'

  app.fabric do |config|
    config.api_key = "api_key"
    config.build_secret = "build_secret"
    config.kit 'Crashlytics'
    config.kit 'AWSCognitoIdentity' do |info|
      info[:AWSCognitoIdentityPoolId] = 'MyPoolId'
      info[:AWSCognitoIdentityRegionType] = 'MyRegionType'
    end
    config.kit 'Appsee' do |info|
      info[:apikey] = 'MyApiKey'
    end
    # config.kit 'Digits' do |info|
    #   info[:consumerKey] = 'MyKey'
    #   info[:consumerSecret] = 'MySecret'
    # end
    config.kit 'GameAnalytics' do |info|
      info['api-key'] = 'MyKey'
      info['api-secret'] = 'MySecret'
    end
    config.kit 'Optimizely' do |info|
      info[:socket_token] = 'MyToken'
    end
    config.kit 'PubNub' do |info|
      info['publish-key'] = 'MyPublishKey'
      info['subscribe-key'] = 'MySubscribeKey'
      info['secret-key'] = 'MySecretKey'
    end
    config.kit 'STPAPIClient' do |info|
      info[:publishable] = 'MyPublishableAPIKey'
    end
    # config.kit 'Twitter' do |info|
    #   info[:consumerKey] = 'MyKey'
    #   info[:consumerSecret] = 'MySecret'
    # end
  end

  app.pods do
    pod 'AWSCognito'
    pod 'Appsee'
    # pod 'Digits'
    pod 'GA-SDK-IOS'
    pod 'mopub-ios-sdk'
    pod 'Optimizely-iOS-SDK'
    pod 'PubNub/Fabric'
    pod 'Stripe'
    # pod 'TwitterKit'
  end
end


# Temporary note:
# TODO when trying to compile, I get the error
#   Errno::ENOENT: No such file or directory @ rb_file_s_mtime - GA-SDK-IOS/GameAnalytics.framework/Resources
#
# This is because there is no `Resources` direcotry, even thought 'GA-SDK-IOS/GameAnalytics.framework/Resources'
# symlinks to it.  So a `File.mtime(x)` fails.
#
# Change the file `/Library/RubyMotion/lib/motion/project/vendor.rb`, line `188` to read
#   if !File.exist?(build_dir) or Dir.glob('**/*').sort.any? { |x| File.exists?(x) && File.mtime(x) > File.mtime(build_dir) }
#
# Currently unable to submit a PR to rubymotion since https://github.com/HipByte/RubyMotion seems
# to be defunct
